/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import controlador.DAOdepartamento;
import java.text.SimpleDateFormat;
import controlador.DAOpersonal;
import controlador.DAOcita;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.cita;
import modelo.cliente;
import modelo.mascota;
import modelo.personal;

/**
 *
 * @author Esteban
 */
public class FRMagenda extends javax.swing.JInternalFrame {
 DAOpersonal de = new DAOpersonal();
 DAOcita obj = new DAOcita();
    /**
     * Creates new form FRMagenda
     */
    public FRMagenda() {
        initComponents();
         Date currentDate = new Date();
        calendar.setMinSelectableDate(currentDate);
        cbohora.removeAllItems();
        cbohora.addItem("10:00:00");
        cbohora.addItem("11:00:00");
        cbohora.addItem("12:00:00");
        cbohora.addItem("15:00:00");
        cbohora.addItem("16:00:00");
        cbohora.addItem("17:00:00");
        cbohora.addItem("18:00:00");
       de.listar_medicos(cbovet);
       btnadd.setEnabled(true);
       cbotipo.removeAllItems();
       cbotipo.addItem("VACUNA");
       cbotipo.addItem("CONSULTA");
       cbotipo.addItem("OPERACIÓN");
    }
 public void setValorTextBox2(String valor3, String valor4 ) {
    lblmascota.setText(valor3);
    lblcod.setText(valor4);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JCalendar();
        txtfecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbohora = new javax.swing.JComboBox<>();
        cbovet = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblmascota = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        lblcod = new javax.swing.JLabel();
        cbotipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Agendar Cita");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Cita Nro:");

        jLabel2.setText("1");

        calendar.setWeekOfYearVisible(false);
        calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calendarMousePressed(evt);
            }
        });
        calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarPropertyChange(evt);
            }
        });
        calendar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calendarKeyPressed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        jLabel4.setText("Hora:");

        cbohora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbohora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbohoraItemStateChanged(evt);
            }
        });
        cbohora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbohoraActionPerformed(evt);
            }
        });

        cbovet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Veterinario");

        jButton1.setText("Seleccionar Mascota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblmascota.setText("..");

        btnadd.setBackground(new java.awt.Color(0, 102, 102));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadd.setText("Guardar Cita");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        lblcod.setForeground(new java.awt.Color(255, 255, 255));
        lblcod.setText("jLabel7");

        cbotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Tipo Cita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblcod)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbohora, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbovet, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblmascota, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcod)
                        .addComponent(cbotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbohora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbovet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblmascota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnadd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /*  void verlista(){
        
        for (cita x:obj.listado()){

            Object v [] = {x.getFecha_hora(), x.getIdveterinario()};         
           
        }
        }*/
    
       
    private void calendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarKeyPressed

    private void calendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarPropertyChange
        
           if ("calendar".equals(evt.getPropertyName())) {
            Date selectedDate = calendar.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = dateFormat.format(selectedDate);
            txtfecha.setText(fecha);
            horascbo();
        }
    }//GEN-LAST:event_calendarPropertyChange

    private void calendarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMousePressed
       
    }//GEN-LAST:event_calendarMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         bsqdamascota obj = new bsqdamascota();
      Home.desktopPane.add(obj);
      obj.toFront();
    obj.setFormulario2(this);    
      obj.setVisible(true);   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbohoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbohoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbohoraActionPerformed

    private void cbohoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbohoraItemStateChanged

       
    }//GEN-LAST:event_cbohoraItemStateChanged
    
    void horascbo (){
String fecha = txtfecha.getText();
String fecha2 = fecha;
modelo.veterinarios d_vo = (modelo.veterinarios) cbovet.getSelectedItem();
int id_ve = d_vo.getId_personal();
SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
Date fechaConvertida;

try {
    fechaConvertida = formato.parse(fecha2);
    ArrayList<String> horasDisponibles = new ArrayList<>();
    ArrayList<String> horasOcupadas = new ArrayList<>();

    for (cita x : obj.listado(fechaConvertida)) {
        SimpleDateFormat formato2 = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat formato3 = new SimpleDateFormat("yyyy-MM-dd");
        String fechaHoraStr = formato2.format(x.getFecha_hora());
        String fechafin = formato3.format(x.getFecha_hora());

        if (x.getIdveterinario() == id_ve) {
            horasOcupadas.add(fechaHoraStr);
        }
    }

    cbohora.removeAllItems();

    cbohora.addItem("10:00:00");
    cbohora.addItem("11:00:00");
    cbohora.addItem("12:00:00");
    cbohora.addItem("15:00:00");
    cbohora.addItem("16:00:00");
    cbohora.addItem("17:00:00");
    cbohora.addItem("18:00:00");

    for (String hora : horasOcupadas) {
        cbohora.removeItem(hora);
    }

} catch (Exception e) {
    e.printStackTrace();
}


  
    }
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
    cita cli = new cita();
        String fecha;
        String hora;
        String fecha_hora;
       fecha = txtfecha.getText();

       
        hora = cbohora.getSelectedItem().toString();
          fecha_hora = fecha+ ' '+ hora;
       
    cli.setIdmascota(Integer.parseInt(lblcod.getText()));
        
  
  
         modelo.veterinarios d_vo = (modelo.veterinarios)this.cbovet.getSelectedItem();
        int id_ve = d_vo.getId_personal();
        cli.setIdveterinario(id_ve);
        cli.setEstado("ACTIVO");
     try {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    Date fechaHora = formato.parse(fecha_hora);
    cli.setFecha_hora(fechaHora);
     } catch (ParseException ex) {
         Logger.getLogger(FRMagenda.class.getName()).log(Level.SEVERE, null, ex);
     }
     String tipo = cbotipo.getSelectedItem().toString();
     cli.setTipo(tipo);
    obj.adicion(cli);
          JOptionPane.showMessageDialog(null, "AÑADIDO CORRECTAMENTE");
dispose();
       
    }//GEN-LAST:event_btnaddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JComboBox<String> cbohora;
    private javax.swing.JComboBox<String> cbotipo;
    private javax.swing.JComboBox<String> cbovet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcod;
    private javax.swing.JLabel lblmascota;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
