/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.table.DefaultTableModel;
import controlador.DAOcliente;
import modelo.cliente;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
/** 
 * @author Esteban
 */
public class FRMbqdacliente extends javax.swing.JInternalFrame {

    DAOcliente obj = new DAOcliente();
   private FRMmascota mascota;
   private FRMmascotaup mascota2;
   private String cliente;
   private String codigo;

    public void setFormulario1(FRMmascota mascota) {
    this.mascota = mascota;
    
    
}
     public void setFormulario2(FRMmascotaup mascota) {
    this.mascota2 = mascota;
    
    
}
    
    public void setValor1(String valor) {
    this.cliente = valor;
}

public void setValor2(String valor) {
    this.codigo = valor;
}
    
    public FRMbqdacliente() {
        initComponents();
        verlista();
        
         cbordenar.removeAllItems();
        cbordenar.addItem("--Seleccione--");
        cbordenar.addItem("Por nombre del cliente");
        cbordenar.addItem("Por apellidos del cliente");
        
    }
     void verlista(){
        DefaultTableModel dt = (DefaultTableModel)tblclientes.getModel();
        dt.setRowCount(0);
        for (cliente x:obj.listado()){

            Object v [] = {x.getIdcliente(), x.getNombre(),x.getApellidos(), x.getSexo(), x.getTdoc(), x.getDni(),x.getTelefono(),x.getCorreo(),x.getDireccion()};         
            dt.addRow(v);
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbordenar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        lblcodigo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Seleccionar Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
        });

        jLabel3.setText("Filtro por DNI");

        txtdni.setToolTipText("");
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdniKeyPressed(evt);
            }
        });

        jLabel1.setText("Ordenar por");

        cbordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbordenar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbordenarItemStateChanged(evt);
            }
        });
        cbordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbordenarActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtro por nombre");

        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "Sexo", "TipoDoc", "NroDoc", "Celular", "Correo", "Dirección"
            }
        ));
        tblclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblclientes);

        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)))
                        .addGap(23, 23, 23)
                        .addComponent(lblcodigo)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcodigo))
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbordenarActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_cbordenarActionPerformed

    private void cbordenarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbordenarItemStateChanged
       String selectedValue = (String) cbordenar.getSelectedItem();
       if (selectedValue == "Por nombre del cliente"){
       sortnombre();
       }else {
       sortapellido();
       }
    }//GEN-LAST:event_cbordenarItemStateChanged

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
         DefaultTableModel dt = (DefaultTableModel) tblclientes.getModel();
dt.setRowCount(0);

String nombreFiltro = txtnom.getText(); // Aquí puedes cambiar el valor por el nombre que deseas filtrar

for (cliente x : obj.listado()) {
    // Aplicar filtro por nombre
    if (x.getNombre().equalsIgnoreCase(nombreFiltro)) {
        Object v[] = {x.getIdcliente(), x.getNombre(), x.getApellidos(), x.getSexo(), x.getTdoc(), x.getDni(), x.getTelefono(), x.getCorreo(), x.getDireccion()};
        dt.addRow(v);
    }
}
        
        }
       
        
        
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtdniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
         DefaultTableModel dt = (DefaultTableModel) tblclientes.getModel();
dt.setRowCount(0);

String nombreFiltro = txtdni.getText(); // Aquí puedes cambiar el valor por el nombre que deseas filtrar

for (cliente x : obj.listado()) {
    // Aplicar filtro por nombre
    if (x.getDni().equalsIgnoreCase(nombreFiltro)) {
        Object v[] = {x.getIdcliente(), x.getNombre(), x.getApellidos(), x.getSexo(), x.getTdoc(), x.getDni(), x.getTelefono(), x.getCorreo(), x.getDireccion()};
        dt.addRow(v);
    }
}
        
        }
    }//GEN-LAST:event_txtdniKeyPressed

    private void tblclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclientesMouseClicked
       int f = tblclientes.getSelectedRow();
        lblcodigo.setText(tblclientes.getValueAt(f, 0).toString());
        String nom = (tblclientes.getValueAt(f, 1).toString());
        String ape = (tblclientes.getValueAt(f, 2).toString());
        String cliente = nom+' '+ape;
       
        
       String valorTextBoxFormulario2 = cliente;
       String codigo = lblcodigo.getText();
    // Establecer el valor en el TextBox del formulario 1
        try {
            mascota.setValorTextBox(valorTextBoxFormulario2,codigo);
     mascota2.setValorTextBox2(valorTextBoxFormulario2,codigo);
        } catch (Exception e) {
        }
    
    
     
     
    // Cerrar el formulario 2
    this.dispose();
        
       
     
       
        
    }//GEN-LAST:event_tblclientesMouseClicked

    
    void sortnombre(){
    DefaultTableModel dt = (DefaultTableModel) tblclientes.getModel();
dt.setRowCount(0);

// Obtener la lista de clientes
List<cliente> listaClientes = obj.listado();

// Ordenar la lista por nombre
Collections.sort(listaClientes, new Comparator<cliente>() {
    @Override
    public int compare(cliente c1, cliente c2) {
        return c1.getNombre().compareTo(c2.getNombre());
    }
});

// Agregar los datos ordenados a la tabla
for (cliente x : listaClientes) {
    Object v[] = {x.getIdcliente(), x.getNombre(), x.getApellidos(), x.getSexo(), x.getTdoc(), x.getDni(), x.getTelefono(), x.getCorreo(), x.getDireccion()};
    dt.addRow(v);
}         // TODO add your handling code here:
    }
    
    
    
        void sortapellido(){
    DefaultTableModel dt = (DefaultTableModel) tblclientes.getModel();
dt.setRowCount(0);

// Obtener la lista de clientes
List<cliente> listaClientes = obj.listado();

// Ordenar la lista por nombre
Collections.sort(listaClientes, new Comparator<cliente>() {
    @Override
    public int compare(cliente c1, cliente c2) {
        return c1.getApellidos().compareTo(c2.getApellidos());
    }
});
for (cliente x : listaClientes) {
    Object v[] = {x.getIdcliente(), x.getNombre(), x.getApellidos(), x.getSexo(), x.getTdoc(), x.getDni(), x.getTelefono(), x.getCorreo(), x.getDireccion()};
    dt.addRow(v);
}         // TODO add your handling code here:
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbordenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
