/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import modelo.raza;
import controlador.DAOraza;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.cliente;
import modelo.mascota;

/**
 *
 * @author Esteban
 */
public class FRMraza extends javax.swing.JInternalFrame {
        DAOraza obj = new DAOraza();
        private FRMmascota mascota;
        private String raza;
   private String codigo;
    /**
     * Creates new form FRMraza
     */
    public void setFormulario2(FRMmascota mascota) {
    this.mascota = mascota;
    
    
}
   
    public FRMraza() {
        initComponents();
        
        
        
    }
    
     public void setValor3(String valor) {
    this.raza = valor;
}

public void setValor4(String valor) {
    this.codigo = valor;
}

    public void setrazavalor(int valor ) {
       int cod = 0;
       cod = valor;
    DefaultTableModel dt = (DefaultTableModel)tblraza.getModel();
        dt.setRowCount(0);
         int valor2 = cod; 
         for (raza x:obj.listado(valor2)){

            Object v [] = {x.getId_raza(), x.getNombre()};         
            dt.addRow(v);
            }
    
}
  
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblraza = new javax.swing.JTable();
        lblcodigo = new javax.swing.JLabel();

        setClosable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblraza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Raza", "Raza"
            }
        ));
        tblraza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrazaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblraza);

        lblcodigo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblcodigo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcodigo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblrazaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrazaMouseClicked
    int f = tblraza.getSelectedRow();
        lblcodigo.setText(tblraza.getValueAt(f, 0).toString());
        String raza = (tblraza.getValueAt(f, 1).toString());
       String valorTextBoxFormulario2 = raza;
       String codigo = lblcodigo.getText();
    // Establecer el valor en el TextBox del formulario 1
     mascota.setValorTextBox2(valorTextBoxFormulario2,codigo);
    dispose();
    }//GEN-LAST:event_tblrazaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tblraza;
    // End of variables declaration//GEN-END:variables
}
